# Generated by Django 3.2.14 on 2022-07-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantherapp', '0002_alter_customuser_id_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Пароль'),
        ),
    ]
