# Generated by Django 3.2.14 on 2022-07-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantherapp', '0004_alter_customuser_id_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_telegram',
            field=models.IntegerField(blank=True, verbose_name='ID пользователя в Telegram'),
        ),
    ]
